Issue 295:  auto delete api activity logs out of retention period
mycloudnexus/kraken pull request #316
Opened 2024-12-24 08:29 UTC by happyiamjoseph

a/c:

kraken can allow user to configure a log retention period like 3 months, 6 months etc
retention period of control plane, stage data plane and prod data plane can be configured differently
retention period for basic data and detail data of api activity can be configured separately
kraken can auto delete api activity detail logs physically out of retention period
user can set to delete detail data for specific method, e.g. only to delete GET data and keep data for other methods
the feature can be disabled and enabled
the auto delete shouldn't impact api activity statistics calculation

https://github.com/mycloudnexus/kraken/issues/295

2025-01-03 07:03 UTC, xuelianhan007 commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/config/AppConfig.java
> +      return logKind == LogKindEnum.DATA_PLANE || logKind == LogKindEnum.CONTROL_PLANE;
Please consider reusing the existed 'PlaneTypeEnum.java'. Thanks.

2025-01-03 07:04 UTC, xuelianhan007 commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/enums/LogKindEnum.java
> +  MANAGE_PLANE("manage-plane");
Please consider reusing the existed 'PlaneTypeEnum.java'. Thanks.

2025-01-03 07:15 UTC, kuangxiang20240501 commented on kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/handler/ClientAPIAuditLogEventHandler.java
> +    return this.apiActivityLogService.receiveClientLog(envId, userId, event);
ApiActivityLogService in core should contain common logic, while  the function receiveClientLog is only used in  control plane,ot including hub and agent.  would  u like restore it.

2025-01-03 07:19 UTC, kuangxiang20240501 commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/config/AppConfig.java
> +    private String protocol;
what does protocol mean? Expected an exmaple.

2025-01-03 07:22 UTC, happyiamjoseph commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/enums/LogKindEnum.java
> +  MANAGE_PLANE("manage-plane");
removed

2025-01-03 07:24 UTC, happyiamjoseph commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/config/AppConfig.java
> +    private String protocol;
added:  
// for example: GET、POST、PATCH、DELETE

2025-01-03 07:25 UTC, happyiamjoseph commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/config/AppConfig.java
> +      return logKind == LogKindEnum.DATA_PLANE || logKind == LogKindEnum.CONTROL_PLANE;
done

2025-01-03 07:33 UTC, happyiamjoseph commented on kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/handler/ClientAPIAuditLogEventHandler.java
> +    return this.apiActivityLogService.receiveClientLog(envId, userId, event);
1、Saving data should be common logic，the high level module call saving when it need. 
Although only control service need to receive api log.  it support other service to reuse.
2、Java sdk provide many method，we choose when we need，we don't choose when we don't need.  we can't ask sdk to remove method if we don't need.
3、Who can guarantee the existed method are all used in data、control、manage?

2025-01-03 07:35 UTC, happyiamjoseph commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/entity/ApiActivityLogEntity.java
> +  private LifeStatusEnum lifeStatus;
They are different and focus diffrentlly.

2025-01-03 07:38 UTC, kuangxiang20240501 commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/ApiActivityLogService.java
> +  public void achieveApiActivityLog(AppConfig.AchieveApiActivityLogConf activityLogConf) {
is the operation included in a transaction. if there exists,  how to handle  lots of data?

2025-01-03 07:43 UTC, happyiamjoseph commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/ApiActivityLogService.java
> +  public void achieveApiActivityLog(AppConfig.AchieveApiActivityLogConf activityLogConf) {
The method process data 20 in a batch.

2025-01-03 08:06 UTC, zhiyaoPCCW commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/ApiActivityLogService.java
> +      if (activityLogConf.getAchieveScope() == AchieveScopeEnum.BASIC) {
What is difference between BASIC and DETAIL and why to seperate achieve action into two different scopes?

2025-01-03 08:09 UTC, kuangxiang20240501 commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/entity/ApiActivityLogEntity.java
> +  private ApiActivityLogBodyEntity apiLogBodyEntity;
Setting with lazy mode  may be better.

2025-01-03 08:14 UTC, zhiyaoPCCW commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/ApiActivityLogService.java
> +  public ApiActivityLogEntity save(ApiActivityLogEntity apiActivityLogEntity) {
Better to add a @Transactional to garentee the consistance.

2025-01-03 08:16 UTC, zhiyaoPCCW commented on kraken-java-sdk/kraken-java-sdk-core/src/test/java/com/consoleconnect/kraken/operator/core/service/ApiActivityLogServiceAtControlPlaneTest.java
> +  void insertLogWithoutSubTable() {
Better to name the test case function name as: 
givenXXX_whenXXX_thenXXX

2025-01-03 08:20 UTC, kuangxiang20240501 commented on kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/handler/ClientAPIAuditLogEventHandler.java
> +    return this.apiActivityLogService.receiveClientLog(envId, userId, event);
It is  easy to get  that the logic is expecially for control  plane  not for others. for example ,  when receiving client logs , the envId  is Meaningful  for control plane.  But hub will not understand what envid  is.

2025-01-03 08:24 UTC, zhiyaoPCCW reviewed
Please  make sure  to clear the code smells.

2025-01-03 08:31 UTC, kuangxiang20240501 commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/config/AppConfig.java
> +    private PlaneTypeEnum logKind;
Due to  every agent use Their own configuration files.  It seems that the logkind is not required

2025-01-03 08:41 UTC, happyiamjoseph commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/ApiActivityLogService.java
> +      if (activityLogConf.getAchieveScope() == AchieveScopeEnum.BASIC) {
Detail contain request、response. Basic contain requestIp、responseIp、callSeq、syncedAt、syncStatus and etc

2025-01-03 08:42 UTC, happyiamjoseph commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/service/ApiActivityLogService.java
> +  public ApiActivityLogEntity save(ApiActivityLogEntity apiActivityLogEntity) {
done

2025-01-06 03:06 UTC, happyiamjoseph commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/config/AppConfig.java
> +    private PlaneTypeEnum logKind;
removed

2025-01-06 03:10 UTC, happyiamjoseph commented on kraken-java-sdk/kraken-java-sdk-controller/src/main/java/com/consoleconnect/kraken/operator/controller/handler/ClientAPIAuditLogEventHandler.java
> +    return this.apiActivityLogService.receiveClientLog(envId, userId, event);
As the data structure is same at data and plane.  saving data should be common logic.  data and control can use or not use.

2025-01-06 03:15 UTC, zhiyaoPCCW requested changes
@happyiamjoseph  Code smells are still not cleared. Please have a look.

2025-01-06 03:23 UTC, kuangxiang20240501 commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/entity/AbstractHttpEntity.java
> +  public Object getRawRequest() {
What is the difference between getRawRequest and  getRequest?

2025-01-06 05:15 UTC, zhiyaoPCCW approved these changes
LGTM

2025-01-06 05:30 UTC, xuelianhan007 approved these changes
GOOD

2025-01-06 05:35 UTC, kuangxiang20240501 approved these changes
LGTM

2025-01-06 05:35 UTC, zhiyaoPCCW approved these changes

2025-01-06 05:35 UTC, merged

2025-01-06 10:08 UTC, michaeltangpub2 commented on kraken-java-sdk/kraken-java-sdk-core/src/main/java/com/consoleconnect/kraken/operator/core/enums/LifeStatusEnum.java
> +  ACHIEVED("ACHIEVED");
typo? archived?